README.md
`nodenv` and `node-build` can now be installed via Homebrew by first tapping [jawshooah/homebrew-nodenv](https://github.com/jawshooah/homebrew-nodenv).
=> Add notice in README about installing via Homebrew

libexec/nodenv-version-name, test/version-name.bats
for node versions, we already accept exact matches as well as the 'node-' prefix:
`NODENV_VERSION=0.10.36` -> `0.10.36`
`NODENV_VERSION=node-0.10.36` -> `0.10.36`
`NODENV_VERSION=iojs-1.0.0` -> `iojs-1.0.0`
now we accept an optional 'v' prefix in the version name:
`NODENV_VERSION=v0.10.36` -> `0.10.36`
`NODENV_VERSION=node-v0.10.36` -> `0.10.36`
`NODENV_VERSION=iojs-v1.0.0` -> `iojs-1.0.0`
(this also applies to `.node-version` files as well, to be clear)
closes #22
=> Accept NODENV_VERSIONs with 'v' prefix

libexec/nodenv, libexec/nodenv-completions, libexec/nodenv-help, libexec/nodenv-init, libexec/nodenv-versions, libexec/nodenv-which, test/completions.bats, test/exec.bats, test/nodenv.bats, test/test_helper.bash, test/which.bats
- use PWD var over pwd command
- indentation
- Extract `abort` helper function
- completions for rbenv-init
- consistent completions for rbenv-help
- completions for rbenv-completions
- completions for rbenv-versions
- add --help to subcommand completions
- handle --help for subcommands
- Fix argument handling in main `rbenv` command
- Explicitly asking for help with `-h` or `--help` exits with 0 status
and displays help on stdout.
- Not providing any arguments to rbenv results in failure status and
displays version and help on stderr.
- Fix broken version-dependent test
- Fix error message when command is not found for "system" version
If `foo` didn't exist and `RBENV_VERSION=system rbenv which foo` was
called, the error message used to be misleading:
rbenv: version `system' is not …
=> Latest updates from rbenv upstream

.gitignore, .gitmodules, .travis.yml, libexec/nodenv---version, libexec/nodenv-help, package.json, script/build-native-ext, test/test_helper.bash
Adds package.json
- install bats via npm instead of git-clone
- install bats-assert via npm instead git-submodule
- switch travis config to use standard node test setup
- defaults to npm-install instead of `install` in travis.yml
- defaults to npm-test instead of `script` in travis.yml
- nodenv---version pulls version from package.json instead of hardcoded
- grab release script (for `preversion`/`postversion` hooks) from node-build (ensures proper git state before bumping version; triggers brew-publish after bump)
- grab brew-publish script from node-build to submit PR to homebrew after each version bump/release
Benefits:
- `npm install` will give us the necessary test dependencies (bats and bats-assert)
- `npm run` will list available scripts
- `npm test` to test
- `npm version <bump>` …
=> Add package.json

libexec/nodenv-sh-shell, test/shell.bats
Keeping rbenv-controlled variables to RBENV_* "namespace" helps with
discoverability (and tools like rbenv-env) but also consistency and a
very minor degree of safety/isolation from env impact.
=> Conforms OLD_RBENV_VERSION to RBENV_* convention

.gitignore
Ignore the required `$(nodenv root)/default-packages` file used by [nodenv-default-packages](https://github.com/nodenv/nodenv-default-packages).
I prefixed the added line with a slash to follow the convention, but I normally would have omitted it. Let me know if you want it removed.
=> Ignore default-packages file

libexec/nodenv-version, test/version.bats
When printing the current node version and its origin (how it was set),
nodenv-version now resolves any symlinks to determine the final
targeted version.
It prints the version name as selected, an arrow and the aliased version
name, and finally the origin.
If the version is not an alias, the output is the same as before.
This only affects the output of `nodenv version`;
`nodenv-version-name` and `nodenv-version-origin` are unaffected.
before:
```
$ NODENV_VERSION=8 nodenv version
8 (set by NODENV_VERSION environment variable)
```
after:
```
$ NODENV_VERSION=8 nodenv version
8 => 8.9.1 (set by NODENV_VERSION environment variable)
```
closes #123
=> nodenv-version learns to describe aliases

libexec/nodenv-version
nodenv prefix system blows up on travis with "node: command not found"
=> Figure out why 'system' node is borked on travis

libexec/nodenv, libexec/nodenv-hooks, libexec/nodenv-versions, test/test_helper.bash
These messages are only printed if NODENV_NATIVE_EXT is set; and it _was_ only
set for test runs. (It is not expected to be set by users.) Thus these
messages are only useful when running on travis, and I'd rather there not
be test-only code running for users.
Also, update the test helper to not use the NODENV_NATIVE_EXT variable
at all, since the travis config no longer uses it. (We build the native
extension as part of npm-install, and have an extra travis job that
immediately removes the compiled executable. Thus, it either exists or
doesn't, for a given test run. There is no variable that declares its
existence.) Instead, just check for the existence of the extension; if
it exists, we should assume it was attempted to be enabled and fail if
accordingly.
=> Remove test-only abort messages

test/completions.bats, test/exec.bats, test/help.bats, test/hooks.bats, test/init.bats, test/prefix.bats, test/rehash.bats, test/shell.bats, test/shims.bats, test/versions.bats, test/whence.bats, test/which.bats
specifically assert_output requires explicit argument to indicate STDIN
=> Migrate from old bats libs

nodenv.d/exec/npx.bash, test/npx.bats, test/test_helper.bash
If npx is being executed, remove nodenv's shims from PATH such that npx
won't find the shims for executables that only exist in non-active
nodes. This ensures npx can install the necessary package on-demand.
PR for #79
=> Adds an exec hook to handle npx specially

libexec/nodenv---version, test/--version.bats
The current output of nodenv --version is essentially the direct output
of git-describe, which is TAG-COMMITS_SINCE_TAG-gSHA.
The commits-since, and sha segments would be considered build metadata
in semver parlance.
This change tweaks the output of git-describe such that it is in a
semver compliant format; despite not strictly being semver compliant in
semantics. (Which isn't really possible with edge/HEAD anyway)
It also eliminates the "g" prefix which is used to denote the sha
references the git SCM.
before/after:
```diff
$ nodenv --version
-nodenv 1.2.0-30-gd57082d
+nodenv 1.2.0+30.d57082d
```
=> Make --version more semver friendly

CONTRIBUTING.md, package.json
Adds some documentation for the uncommon configuration necessary for having both nodenv and rbenv remotes in the same repo.
=> Adds Contributing doc

libexec/nodenv-versions, test/versions.bats
Closes #118 
This contains the feature changes from #118 plus some additional tests. Opening as a separate PR to make it easier to merge the combination of both.
=> Handle version aliases within an lts directory (replaces #118)

README.md
An initial attempt to add documentation around the feature from #154 
_Note: The documented feature is currently not yet released outside of `nodenv` installations via the git `master` branch. It probably makes sense to only merge this close to the actual wider release._
=> Add documentation for lts/ folder support in nodenv versions

README.md
nodenv doesn't have any debian/ubuntu packages available.
fixes #208
=> Remove debian instructions

.github/workflows/sync-default-branch.yml
Workflow to continue syncing master branch whenever main advances. This will prevent clones of this repo from breaking.
=> Renamed master->main

README.md, libexec/nodenv-version-file-read, test/test_helper.bash
Update nodenv to rbenv/rbenv@c4395e58201966d9f90c12bd6b7342e389e7a4cb
- **Update code block in readme for rbenv-doctor script (#1353)**
- **Use test -aP instead of which -a in test helper**
- **Make bash commands copy-able by GitHub**
- **Remove the word "groom" from documentation**
- **README: grammar fix**
- **Redirect Debian/Ubuntu users to install using git**
- **Fix indentation in installation instructions**
- **Don't bother reading empty version files**
- **Simplify version file read**
- **Fix link to Pow because the server is down**
=> rbenv upstream

package.json
npm-pkg-fix
```
npm WARN publish npm auto-corrected some errors in your package.json when publishing.  Please run "npm pkg fix" to address these errors.
npm WARN publish errors corrected:
npm WARN publish "bin" was converted to an object
npm WARN publish "bin[@nodenv/nodenv]" was renamed to "bin[nodenv]"
npm WARN publish "bin[nodenv]" script name was cleaned
npm WARN publish "repository.url" was normalized to "git+https://github.com/nodenv/nodenv.git"
npm WARN publish Normalized git reference to "devDependencies.bats-assert"
npm WARN publish Normalized git reference to "devDependencies.bats-support"
```
=> Fix npm pkg warnings

CONTRIBUTING.md, package.json
using `rbtags` since it's shorter and doesn't distinguish between rbenv and ruby-build (since we also use this at node-build).
=> Move rbenv tags to rbtags namespace

Makefile, package-lock.json, package.json, script/sync-version, share/man/man1/nodenv.1
- Pins a dep instead of relying ons system deps.
- Uses npm package script (npm run man) instead of Makefile.
- Hooks into npm package lifecycle to ensure the version files are updated correctly when `npm version` bumping. (And files are added to the tagged commit.)
- registers the manpages with npm so they're installed (despite [npm's bug](https://github.com/orgs/community/discussions/167663))
fixes #257
=> Use asciidoctor.js for manpage generation
