nodenv/nodenv

libexec/nodenv-help
libexec/nodenv-init
libexec/nodenv-versions
libexec/nodenv-which
test/init.bats
test/versions.bats
test/which.bats

This merge is from f4652fbbf0bbc3d07a36e8781b2be54ec1f75518 which gets us to Oct 2014.

Merge in some updates from rbenv upstream

---

README.md

Small change to avoid confusion.

Remove reference to "gem".

---

README.md
libexec/nodenv-init
test/init.bats

Rbenv updates

---

libexec/nodenv---version
package.json
script/build-native-ext

Embed the version into nodenv---version (bumped via `npm version`)
Tweak publish scripts.
build script to compile the native extension

Fix up some scripts

---

package.json
script/release-github
script/release-precheck

Add release script from node-build

---

package.json

Build native extension on install

---

README.md
completions/nodenv.fish
libexec/nodenv
libexec/nodenv-commands
libexec/nodenv-help
libexec/nodenv-init
libexec/nodenv-prefix
libexec/nodenv-rehash
libexec/nodenv-root
libexec/nodenv-version-file
libexec/nodenv-version-file-read
libexec/nodenv-whence
libexec/nodenv-which
src/configure
test/prefix.bats
test/shell.bats
test/version-file.bats
test/version-origin.bats
test/which.bats

Includes: rbenv/rbenv#1098 rbenv/rbenv#1093 rbenv/rbenv#1083     rbenv/rbenv#1069 rbenv/rbenv#981 rbenv/rbenv#1013 rbenv/rbenv#968     rbenv/rbenv#959 rbenv/rbenv#982 rbenv/rbenv#1002 rbenv/rbenv#1003     rbenv/rbenv#1024 rbenv/rbenv#1034 rbenv/rbenv#1009 rbenv/rbenv#1011

Merge latest changes from rbenv/master

---

.travis.yml
package-lock.json
package.json
script/build
script/clean
script/preversion
script/publish/github
script/version/sync

Prepare for npm publishing

---

package-lock.json
package.json
test/--version.bats
test/completions.bats
test/exec.bats
test/global.bats
test/help.bats
test/hooks.bats
test/init.bats
test/local.bats
test/nodenv.bats
test/prefix.bats
test/rehash.bats
test/shell.bats
test/test_helper.bash
test/version-file-read.bats
test/version-file-write.bats
test/version-file.bats
test/version-name.bats
test/version-origin.bats
test/version.bats
test/versions.bats
test/whence.bats
test/which.bats

Switch to ztombol's bats libs

---

libexec/nodenv-versions
test/versions.bats

Fixes #103
This sort function should be replicated to node-build

Sort versions output semantically

---

README.md

Uses https://github.com/apps/toc-me and replaces #88

Insert toc-me generated TOC

---

libexec/nodenv-versions
test/versions.bats

Fix incorrect count of versions in `nodenv versions`

---

README.md

Add an explanation for "nodenv init"

---

README.md

Fix wrong symlink example in Readme

---

.github/workflows/release.yml
.github/workflows/test.yml

Bump GH Actions

---

README.md

Remove and update old rbenv text

---

.github/workflows/release.yml
.github/workflows/sync-default-branch.yml
.github/workflows/test.yml

- **Restrict default permissions and upgrade test job**
- **Streamline hardener config**
- **Prettier format yaml**
- **Bump to latest test workflow**

Bump to latest nodenv test workflow

---

README.md
test/rehash.bats
test/which.bats

- acdd8a95bd961f8f873a685c5bb3879ab03d38c0
- 009ef3a2db0d4c6bd704d38cf619cfed3f146bcd
- rbenv/rbenv#1436
- 396e65a4612203d81c68d413a783116ce64c8402
- 45ae8d2ebc46461ae361925d81cfa3caffcfe686
- 7c7c4dc11cd30637d40f7a7324ca8200215fb69f
followup with #253

Pull updates from rbenv upstream (~1.3.0)

---

Makefile
README.md
libexec/nodenv-commands
libexec/nodenv-help
test/which.bats

- rbenv/rbenv#1583
- rbenv/rbenv#1587
- rbenv/rbenv#1598
- rbenv/rbenv#1600
- rbenv/rbenv#1604

Merge updates from rbenv 1.3.1

---

libexec/nodenv-commands
libexec/nodenv-help

Pull updates from rbenv 1.3.2
